### ISSUE TITLE
python environment only doing PRISM

### ISSUE THREAD

**Issue by matkraj** [prism-em/prismatic#1]
Hi,  when I try to run the simulation in python (jupyter-ntb), only prism algorithm works - it seems the code does not register tag meta.algorithm = 'multislice'

Is it hard coded here? 
https://github.com/prism-em/prismatic/blob/efe17c26a05ae4ee3ec559596d214901fab5b0d7/pyprismatic/core.cpp#L132-L135
and
https://github.com/prism-em/prismatic/blob/efe17c26a05ae4ee3ec559596d214901fab5b0d7/pyprismatic/core.cpp#L153

**Comment by apryor6** [comment]
Good catch, looks like some kind of accidental cut/paste error. I fixed this in the latest commit and reuploaded to PyPi
