### ISSUE TITLE
Some GUI settings reset after simulation

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#10]
The options for Algorithm and Slice thickness reset between each simulation. This caught me out a couple of times.

**Comment by thomasaarholt** [comment]
Hm, this doesn't always seem to be the case. It might be just when I've run it as multislice. Will do some digging.

**Comment by apryor6** [comment]
I tested around and was never able to reproduce this, so I'm closing the issue. If you can reproduce the error, please feel free to reopen and I will look again.
