### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by apryor6** [prism-em/prismatic#14]
It would be useful for us to establish a mailing list for users. I just released v1.1 of `Prismatic`, and it is available from prism-em.com, but we don't currently have a good way to notify people.

**Comment by apryor6** [comment]
A google group could work, but I’ve less experience with best practices for this sort of thing.

**Comment by thomasaarholt** [comment]
Googlegroups tend to work well. Both Hyperspy and my sports team use them, and they're easy to use and maintain.

**Comment by lerandc** [comment]
Closing for now-- will reopen if there is interest in mailing group still!
