### ISSUE TITLE
SI100.XYZ not part of Prismatic CPU windows version

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#17]
Absolutely minor, but I spotted that the SI100.XYZ file is not in the root folder of the non-GPU installation of Prismatic on Windows.

**Comment by apryor6** [comment]
[SI100.XYZ](https://github.com/prism-em/prismatic/raw/master/SI100.XYZ)

Thanks -- I'll fix in the future. For now the file is linked above.
