### ISSUE TITLE
Orientations of x and y

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#20]
I just spotted the following unexpected relation between x and y with the order of image dimensions. It tricked me since I was using an orthorhombic unit cell with very similar a and b lengths, and things weren't being calibrated correctly. Thoughts?

Example is made to emphasise the relationship, I'm not actually using those values.

![image](https://user-images.githubusercontent.com/2721423/34560991-666495ae-f148-11e7-9e16-b3cae78e1f7d.png)

**Comment by apryor6** [comment]
This is the intended behavior, though this subject is always a pain. `Prismatic`, like many softwares, uses C-style ordering for arrays such that the fastest changing index is X, then Y, then Z, etc. However when displaying images it is common for the origin the be at the top left, the first index to represent the row and the second index to represent the column. This is what MATLAB and NumPy's Matplotlib do, for instance. So the result is that X is increasing along the downward screen direction, and Y increases towards the right. There is more detail about multidimensional arrays in Prismatic [here](http://prism-em.com/source-code/#multidim-arrays).
