### ISSUE TITLE
multiple frozen phonon not calculated/exported in gui app 

### ISSUE THREAD

**Issue by matkraj** [prism-em/prismatic#21]
There seems to be a bug in gui app.

- I get two _.mrc_ files with frozen phonon (`-F 2`)  when I run `./prismatic -i "./STO.xyz" -t 10 10 10 -o "cli-single.mrc" -wx 0.5 0.5 -wy 0.5 0.5 -a m -4D 1 -3D 0 -p 0.1 -sa 15 -A 40 -r 1 -F 2 -s 1 -E 300 -P 2 -oc 1`

- I only get a single file when I run gui:
![gui_settings](https://user-images.githubusercontent.com/32445707/34854240-956d481a-f78c-11e7-9b58-d4ac11d445fe.png)

STO.xyz:

> lala 
3.905   3.905   3.905
38 0.00000000 0.00000000 0.00000000   1   0.08
22 1.95250000 1.95250000 1.95250000   1   0.08
8 0.00000000 1.95250000 1.95250000   1   0.08
8 1.95250000 0.00000000 1.95250000   1   0.08
8 1.95250000 1.95250000 0.00000000   1   0.08
-1

**Comment by apryor6** [comment]
Probably an incrementing error. I’ll look into it
