### ISSUE TITLE
Impact of cellDimX...Y...Z in pyprismatic

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#25]
For each simulation I do, I dump the entire Metadata dictionary into metadata in a hdf5 file. I just noticed that for my simulation files, the cellDimX, cellDimY and cellDimZ entries are all set to the standard value of 20Å, for simulations which had different cell dimensions.

```python
>>> meta=pr.Metadata()
>>> meta.cellDimX
20.0
```

I had up till now just assumed that when I loaded an xyz file with pyprismatic, it read off the first three values in the file, which are cellDimX, cellDimY and cellDimZ, and used them.

I assume that is it's actual behavior, and that overwriting the (unnecessary??) cellDim parameters in the Metadata just hasn't been implemented?

Or do I need to manually enter the parameters? That seems tedious.

**Comment by apryor6** [comment]
Cell dimensions can either be provided explicitly by the user or, by default, are read from the input coordinate file. It is assumed if the user provides values that the cell dimensions from the input file are to be ignored. In implementation, the reading of the coordinate file occurs after argument parsing, so there is an additional flag, `userSpecifiedCelldims` that signals whether or not to overwrite the cell dimensions. 

However, as you have noticed, this flag is not implemented in the Python wrapper, and the only available behavior is reading parameters from the coordinate file. Thus, the implementation is currently incomplete, and it would be better to either remove those dimensions as parameters entirely or, better yet, to properly implement the same behavior that the CLI has.
