### ISSUE TITLE
HDF5 Support

### ISSUE THREAD

**Issue by apryor6** [prism-em/prismatic#3]
A suitable HDF5 format such as EMD would be vastly superior to the current choice of outputting many smaller files, particularly for the 4D output

**Comment by cophus** [comment]
Of course I would also vote in favour of EMD format:
https://emdatasets.com/

Another major advantage of HDF5 (whether EMD or no) is packaging up all of the simulation outputs into a single file.  These include the parameter files, the 3D and / or 4D outputs, projected potentials, atomic coordinates, or even the multislice vs PRISM validation simulation(s).

**Comment by lerandc** [comment]
HDF5 has been implemented!
