### ISSUE TITLE
Re-read defocus from params off by factor 1000

### ISSUE THREAD

**Issue by apryor6** [prism-em/prismatic#30]
Parameter file written/reread results in defocus off by a factor of 1000

**Comment by HamishGBrown** [comment]
The offending line is 187 of parseInput.cpp:

[`
        f << "--probe-defocus:" << meta.probeDefocus * 1000 << '\n';
`](https://github.com/prism-em/prismatic/blob/master/src/parseInput.cpp#L187)

The factor of 1000 should not be there.
