### ISSUE TITLE
4D outputs are not scaled correctly

### ISSUE THREAD

**Issue by cophus** [prism-em/prismatic#32]
When saving each probe position (4D output), the output is not scaled correctly.  Each image should be multiplied by:

(-fx)^2 * (-fy)^2
i.e the two interpolation factors multiplied and squared.

Note the 3D outputs are correctly scaled - this issue only affects the 4D outputs.

**Comment by thomasaarholt** [comment]
Are you sure that is correct? I am assuming that the total intensity for a given diffraction image should = 1.
The attached file use interpolation factors = 2
`pr.fileio.readMRC("test1_X0_Y0_FP1.mrc").sum() = 0.0001985`
Using the approach you suggest would give 0.0001985 * (-2)^2 * -(2)^2 = 0.003176, which is very low.

The reciprocal of the summed intensity is 5036, which, if one assumes some loss, is close to 4096. 4096 == 8^2*8^2.


[test1_X0_Y0_FP1.zip](https://github.com/prism-em/prismatic/files/2538980/test1_X0_Y0_FP1.zip)
Output of meta.toString():

```
interpolationFactorX = 2
interpolationFactorY = 2
filenameAtoms = OrthZnO_Prismatic_RT.xyz
filenameOutput = Results\test1.mrc
realspacePixelSizeX = 0.025
realspacePixelSizeY = 0.025
potBound = 2.0
numFP = 1
sliceThickness = 1.0
cellDimX = 20.0
cellDimY = 20.0
cellDimZ = 20.0
tileX = 2
tileY = 2
tileZ = 1
E0 = 300000.0
alphaBeamMax = 0.012
numGPUs = 4
numStreamsPerGPU = 3
numThreads = 12
batchSizeTargetCPU = 1
batchSizeTargetGPU = 2
earlyCPUStopCount = 100.0
probeStepX = 0.25
probeStepY = 0.25
probeDefocus = 0.0
C3 = 0.0
C5 = 0.0
probeSemiangle = 10.0
detectorAngleStep = 0.001
probeXtilt = 0.0
probeYtilt = 0.0
scanWindowXMin = 0.0
scanWindowXMax = 0.49999
scanWindowYMin = 0.0
scanWindowYMax = 0.49999
randomSeed = 203963
algorithm = prism
includeThermalEffects = True
alsoDoCPUWork = True
save2DOutput = False
save3DOutput = True
save4DOutput = True
integrationAngleMin = 0
integrationAngleMax = 0.001
transferMode = auto
```
