### ISSUE TITLE
Segmentation fault running pyprismatic+GPU code 

### ISSUE THREAD

**Issue by robtovey** [prism-em/prismatic#35]
Core prismatic is installed and runs fine but the pyprismatic.demo code crashes with a segmentation fault for me. See the full printout below.
I suspect that this is my own fault, I have a slightly complicated setup, but thought I should raise the issue and see if anyone had suggestions.

I installed prismatic (ubuntu, cuda 8.0) via command line and this works fine. I can use prismatic from the command line or GUI. I suspect the issue with python is that it has its own cuda version (7.5) installed through anaconda which may be confusing paths or something. I installed pyprismatic via setup.py (I tried cuda 8.0 on global path and linked at compile time) but maybe it compiled with one version and is finding the other version at runtime?

My solution at the moment is just to run via subprocess and this runs the same in practice. This is a bit strange because I think subprocess actually inherits the same path variables as python so it shouldn't be a path issue. 

If anyone is interested, the resulting code looks something like:
```
    mystr = ['--' + key + ' ' + str(prismatic_kwargs[key])
             for key in prismatic_kwargs]
    subprocess.call('prismatic ' + ' '.join(mystr), shell=True)
    meta = readMRC(prismatic_kwargs['output-file'])
```
where prismatic_kwargs is just a dictionary of the command line variables.

My solution is perfectly workable at the moment and should work on any other computer with prismatic installed so I'm not too worried about fixing this, especially as it looks to me like it may be a personal issue rather than general. On the other hand, if anyone has some ideas then I'm happy to try stuff on my end if that helps.

Thanks for your help.
All the best,
Rob

![image](https://user-images.githubusercontent.com/39965511/42944124-b8688a78-8b5c-11e8-94c0-b4676dd6ca45.png)

**Comment by apryor6** [comment]
You can find out what libraries your compiled files linked against with `ldd`. If you run that command against the compiled prism executables and libraries, you will see which version of CUDA was linked against. At runtime, the executables and libraries are found via `PATH` and `LD_LIBRARY_PATH` variables, so if your prismatic libraries are compiled against 8.0, but your path variables find 7.5, then this will cause segmentation fault issues. Segfaults can be painful to debug as there is usually no helpful error messages, but in my experience usually they are due to inconsistencies between versions of libraries compiled against vs found at runtime.

**Comment by robtovey** [comment]
This seems to be the case. prismatic, prismatic-gui and libcuprismatic have all been compiled from the main path but core manages to get compiled with the anaconda version. If this is what happens when running setup.py I imagine it happens all the time.
I've tried playing with PATH and PYTHONPATH but this doesn't seem to affect however python finds the cuda libraries. If you don't have any other suggestions then I'm happy to consider this closed?

**Comment by apryor6** [comment]
Are you using Anaconda as your primary Python, or do you have it installed alongside for other reasons? I believe following the `setup.py` installation route should install to whatever python is used when you invoke the command. I have run into clashes before between using Anaconda Python and basically any package that is not supported directly by Anaconda. If you end up in a situation where you have multiple Pythons installed (especially if you are not using virtual environments) in addition to having multiple CUDA versions available there are many possible sources of issue. Part of the Anaconda installation process modifies path variables in ~/.bashrc in a way that is not obvious unless you expect it, which can be frustrating to debug. Similar messes can happen if you are on Mac and mix Anaconda with Homebrew Python. For this reason I stopped using Anaconda altogether a long time ago in favor of keeping a single installation and managing the path modifications myself (or just using virtualenv).

**Comment by robtovey** [comment]
Yes, Anaconda is my primary Python and I'm not using any virtual environments. Hm, I started with Anaconda because it promises a lot but I've gradually come to realise that it's great when it works but as soon as something goes wrong, the added complexity just makes everything much worse.

Do you have any suggestions for looking at/editing the paths that Anaconda's manipulating?

Also, I've just installed everything on a fresh desktop yesterday and everything works fine. The only difference that I'm aware of was that I just used the native python.

**Comment by apryor6** [comment]
As I recall, Anaconda adds a couple of lines to ~/.bashrc (linux) or ~/.bash_profile (mac) that prepend the Anaconda paths to your PATH variable. That might be all you need to modify. Note if you uninstall Anaconda it will likely remove these lines. If you remove them but leave Anaconda install it will mess up your Anaconda installation should you need it, so I would recommend just commenting these lines out to test.

As I said I think that's all, but the only other variables you *could* need to check would be `LD_LIBRARY_PATH` (on mac this is called `DYLD_LIBRARY_PATH`), `LIBRARY_PATH`, `CPLUS_INCLUDE_PATH`, and `PYTHONPATH`. This is true for pretty much any software on a Unix system -- if I get an error related to finding some library I would check these path-like variables first.

On Windows the variables are `PATH`, `INCLUDE`, and `LIB`.

Glad trying a fresh install helped, compiling code can be tedious.

**Comment by thomasaarholt** [comment]
I installed cupyprismatic on an Anaconda python without trouble. 

I find it very helpful to make use of the Anaconda Environments when doing this, so if you aren't using them, I encourage you to do so. I keep a clean base (root) environment, and only install in any other environments. This makes it easier to keep track of what's in my PATH.

Just to be super clear, Anaconda does not affect any of the other system variables (other than PATH) that @apryor6 refers to above.
