### ISSUE TITLE
Cuda 9/10?

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#45]
The IT department is wanting researchers to play on their new GPU nodes, which consist of 28 CPU cores, 128 GiB RAM and 4 x NVIDIA RTX 2080 Ti cards, running Ubuntu 16.

For now they only have CUDA 9/10, with no SLURM/module loading system.

Has anyone tried compiling with CUDA 9/10? Or am I best off contacting IT and asking them to install the necessary software? I will already need them to install CMake, for instance, so I will be contacting them nonetheless.

**Comment by thomasaarholt** [comment]
Well, I have just successfully compiled and run prismatic with gcc 5.3.0 and Cuda 9.0.

This was my recipe:
```

module purge
module load cmake

module load cuda/9.0

export PATH=$HOME/fftw_gcc5_build:$HOME/fftw_gcc5_build/include:$HOME/fftw_gcc5_build/lib64:$PATH
export CPLUS_INCLUDE_PATH=$CUDA/include:$HOME/fftw_gcc5_build/include:/cluster/software/boost:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$HOME/fftw_gcc5_build/lib64:$CUDA/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=$HOME/fftw_gcc5_build/lib64:$CUDA/lib64:$LD_LIBRARY_PATH

export CC=/cluster/software/VERSIONS/gcc-5.3.0/bin/gcc
export CXX=/cluster/software/VERSIONS/gcc-5.3.0/bin/g++
```
I then compiled fftw with gcc 5.3.0.
When using ccmake for prismatic, I had to specify the fftw library and fftw threads library (same directory) - ccmake found the correct directory for fftw's `include` folder but not the library folders.

From then on it was smooth sailing.

**Comment by apryor6** [comment]
Great, thanks!

**Comment by thomasaarholt** [comment]
Successfully compiled with CUDA 10 as well.
