### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#50]
I sometimes get a `Floating point exception` during `Computing compact S matrix`. I've created this issue here in case anyone explain why it occurs, or at least so that I can add any relevant details I notice.

**Comment by thomasaarholt** [comment]
Hm, it appears to be related to having `alsoDoCPUWork=True`, but with 0 threads specified (running on multiple GPUs though). Setting the above to `False` makes it run.

**Comment by lerandc** [comment]
Similar to Issue #51, did this occur on PyPrismatic?

**Comment by thomasaarholt** [comment]
Yes.

**Comment by lerandc** [comment]
See follow up in #51
