### ISSUE TITLE
Issue in compiling prismatic using GCC version 4.8

### ISSUE THREAD

**Issue by Quantumstud** [prism-em/prismatic#67]
I am trying to compile to the Prismatic source code. I am having issues compiling using the gcc-4.8 
`[ 21%] Building NVCC (Device) object CMakeFiles/prismatic.dir/src/prismatic_generated_PRISM02_calcSMatrix.cu.o
[ 21%] Building NVCC (Device) object CMakeFiles/prismatic.dir/src/prismatic_generated_Multislice_calcOutput.cu.o
[ 21%] Building NVCC (Device) object CMakeFiles/prismatic.dir/src/prismatic_generated_utility.cu.o
[ 21%] Building NVCC (Device) object CMakeFiles/prismatic.dir/src/prismatic_generated_PRISM03_calcOutput.cu.o
Scanning dependencies of target prismatic
[ 26%] Building CXX object CMakeFiles/prismatic.dir/src/driver.cpp.o
[ 31%] Building CXX object CMakeFiles/prismatic.dir/src/WorkDispatcher.cpp.o
[ 36%] Building CXX object CMakeFiles/prismatic.dir/src/configure.cpp.o
[ 47%] Building CXX object CMakeFiles/prismatic.dir/src/PRISM02_calcSMatrix.cpp.o
[ 52%] Building CXX object CMakeFiles/prismatic.dir/src/Multislice_calcOutput.cpp.o
[ 52%] Building CXX object CMakeFiles/prismatic.dir/src/PRISM01_calcPotential.cpp.o
[ 57%] Building CXX object CMakeFiles/prismatic.dir/src/PRISM03_calcOutput.cpp.o
[ 63%] Building CXX object CMakeFiles/prismatic.dir/src/PRISM_entry.cpp.o
[ 68%] Building CXX object CMakeFiles/prismatic.dir/src/Multislice_entry.cpp.o
[ 73%] Building CXX object CMakeFiles/prismatic.dir/src/projectedPotential.cpp.o
[ 78%] Building CXX object CMakeFiles/prismatic.dir/src/parseInput.cpp.o
[ 84%] Building CXX object CMakeFiles/prismatic.dir/src/utility.cpp.o
[ 89%] Building CXX object CMakeFiles/prismatic.dir/src/atom.cpp.o
[ 94%] Building CXX object CMakeFiles/prismatic.dir/src/go.cpp.o
[100%] Linking CXX executable prismatic
/usr/bin/ld: CMakeFiles/prismatic.dir/src/Multislice_calcOutput.cpp.o: undefined reference to symbol '_ZNSo9_M_insertIdEERSoT_@@GLIBCXX_3.4.9'
//home/tara/anaconda3/lib/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/prismatic.dir/build.make:491: recipe for target 'prismatic' failed
make[2]: *** [prismatic] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/prismatic.dir/all' failed
make[1]: *** [CMakeFiles/prismatic.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

-----------------------------------------------------------------------------------------------------------------------
Ironically when I change the gcc version to 7.4.0. It is built. However, this gcc cannot compile the GPU version.
---------------------------------------------------------
`(base) tara@tara-XPS-8930:~/Downloads/STEMSoftwares/Simulation/PRISM/prismatic-master/build$ make -j 8
Scanning dependencies of target prismatic
[ 13%] Building CXX object CMakeFiles/prismatic.dir/src/PRISM01_calcPotential.cpp.o
[ 13%] Building CXX object CMakeFiles/prismatic.dir/src/WorkDispatcher.cpp.o
[ 20%] Building CXX object CMakeFiles/prismatic.dir/src/PRISM02_calcSMatrix.cpp.o
[ 26%] Building CXX object CMakeFiles/prismatic.dir/src/driver.cpp.o
[ 33%] Building CXX object CMakeFiles/prismatic.dir/src/configure.cpp.o
[ 40%] Building CXX object CMakeFiles/prismatic.dir/src/Multislice_calcOutput.cpp.o
[ 46%] Building CXX object CMakeFiles/prismatic.dir/src/PRISM03_calcOutput.cpp.o
[ 53%] Building CXX object CMakeFiles/prismatic.dir/src/PRISM_entry.cpp.o
[ 60%] Building CXX object CMakeFiles/prismatic.dir/src/Multislice_entry.cpp.o
[ 66%] Building CXX object CMakeFiles/prismatic.dir/src/parseInput.cpp.o
[ 73%] Building CXX object CMakeFiles/prismatic.dir/src/projectedPotential.cpp.o
[ 80%] Building CXX object CMakeFiles/prismatic.dir/src/utility.cpp.o
[ 86%] Building CXX object CMakeFiles/prismatic.dir/src/atom.cpp.o
[ 93%] Building CXX object CMakeFiles/prismatic.dir/src/go.cpp.o
[100%] Linking CXX executable prismatic
[100%] Built target prismatic`

-------------------------------------------------------------------------------------------------------------------

**Comment by Quantumstud** [comment]
Hi! 
I found the problem was with the HDF5 installation. CMake was not able to find the libraries installed. The HDF5 libraries have to be re-compiled using the gcc-4.8. The libraries compiled with gcc-7 won't work with gcc-4.8 which is why gcc-7 worked, and gcc-4.8 didn't. So I recompiled HDF5 using the gcc-4.8.

### Just an additional suggestion CMake might often fail to find the HDF5 libraries One way would be setting the environment variable to set the library location of the HDF5 installation. However, the more natural way is to use the following command during the configuration of HDF5 package. 

Go to the top directory of the downloaded HDF5 folder.
`./configure --prefix=/usr/local --enable-shared --enable-hl --enable-threadsafe--enable-cxx --enable-unsupported
make -j 2
sudo su
make install`

This will install both the static and shared libraries in the folders which can be accessed by CMake easily and helps us to save the tiring process of setting the environment variable.

I hope this helps anyone who faces the similar compilation issue.

**Comment by lerandc** [comment]
Thanks for passing along your solution to the issue! I will add a note to the main website that clarifies this compilation issue.

**Comment by apryor6** [comment]
Thanks for sharing resolution.
