### ISSUE TITLE
defocus in input parameter is mrad! or Angstrom?

### ISSUE THREAD

**Issue by reiszadeh** [prism-em/prismatic#68]
Hi
defocus in input parameter is in mrad! but in pyprismatic is in Angstrom.
in all documents defocus present in Angstrom. I wonder if how  can we calculate it based on angle when its units is length?

**Comment by thomasaarholt** [comment]
It should definitely be angstrom. You literally cannot represent defocus as an angle AFAIK.

Where did you see this?

**Comment by reiszadeh** [comment]
in input parameters :+1: 
–probe-defocus (-df) value : probe defocus (in mrad) (default: 0)

**Comment by apryor6** [comment]
Thomas is correct, and this is a typo

**Comment by reiszadeh** [comment]
OK. Thank you...
