### ISSUE TITLE
The simulation metadata are empty

### ISSUE THREAD

**Issue by ericpre** [prism-em/prismatic#75]
The simulation metadata are supposed to be saved in the group `/4DSTEM_experiment/metadata/metadata_0/original/simulation_parameters` but all the key-value pairs are empty!

To repoduce:
```
prismatic -i SI100.XYZ
```

```python
import h5py

f = h5py.File('output.h5', 'r')
md = f.get('4DSTEM_simulation/metadata/metadata_0/original/simulation_parameters')

print(md)
<HDF5 group "/4DSTEM_simulation/metadata/metadata_0/original/simulation_parameters" (0 members)>
```

**Comment by lerandc** [comment]
Hi @ericpre, it looks like a bit of semantics confusion with h5py. The metadata are stored in the group attributes, so to access them `md.attrs`, which can be listed out by 'md.attrs.keys()'

for self-reference/documentation updating:
List all simulation parameters and values (h5py method):
`import h5py
fp = "output.h5"
f = h5py.File(fp, 'r')
md = f.get('4DSTEM_simulation/metadata/metadata_0/original/simulation_parameters')
for key in md.attrs.keys():
    print(key, md.attrs[key]) #prints string values as byte strings`

**Comment by ericpre** [comment]
Yes, I think that I misread the documentation that day and miss the attributes bit, this is indeed working fine (https://github.com/hyperspy/hyperspy/pull/2396/files#diff-9a9e452522a6c34ae2dd3782a26581d2R719-R735), forgot to close this issue - sorry for the noise!

**Comment by ericpre** [comment]
While you are here, could you please review some of the open PRs (when you have time)? :)

**Comment by lerandc** [comment]
Yes, certainly!
